spring:
  application:
    name: rlock
  redis:
    redisson:
      config:
        singleServerConfig:
#          password: 123456
          address: "redis://127.0.0.1:6379"
          database: 1
          threads: 0
          nettyThreads: 0
          transportMode: "NIO"
