server:
  port: 8090
dubbo:
  application:
    name: biz
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    timeout: 4000
spring:
  main:
    allow-bean-definition-overriding: true
